# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

# Meta dependency
kotlin_version=2.0.0

# Mod properties
mod_version = 1.0.0
mod_id = pirates
maven_group = ace.actually.pirates
archives_base_name = pirates
enabled_platforms = fabric,forge

# Minecraft properties
minecraft_version = 1.20.1

# Dependencies
architectury_api_version = 9.1.12
fabric_loader_version = 0.14.24
fabric_api_version = 0.90.7+1.20.1
forge_version = 47.4.10

# VS dependencies
vs2_version=2.4.0+7e18c81efc
vscore_version=1.1.0+3434464932

# Kotlin platform dependencies
kotlin_forge=4.11.0
kotlin_fabric=1.11.0+kotlin.2.0.0

# Leave blank, only ever set in CI tasks.
vs_maven_url=
vs_maven_username=
vs_maven_password=
