architectury {
    common rootProject.enabled_platforms.split(',')
}

loom {
    accessWidenerPath = file("src/main/resources/pirates.accesswidener")
}

test {
    useJUnitPlatform()
}

sourceSets {
    test.kotlin.srcDirs += "src/test/kotlin"
}

dependencies {
    // We depend on Fabric Loader here to use the Fabric @Environment annotations,
    // which get remapped to the correct annotations on each platform.
    // Do NOT use other classes from Fabric Loader.
    modImplementation "net.fabricmc:fabric-loader:$rootProject.fabric_loader_version"

    implementation(("io.github.llamalad7:mixinextras-common:0.4.1"))

    // Architectury API. This is optional, and you can comment it out if you don't need it.
    modImplementation "dev.architectury:architectury:$rootProject.architectury_api_version"

    compileOnly "maven.modrinth:eureka:1.20.1-fabric-1.5.1-beta.3"
    compileOnly "maven.modrinth:valkyrien-sails:1.20.1-0.1.6-fabric"
    compileOnly "maven.modrinth:vlib:1.20.1-0.1.0+fabric"

    modApi("org.valkyrienskies:valkyrienskies-120-common:${rootProject.vs2_version}") {
        exclude group: "com.simibubi"
        exclude group: "io.github.fabricators_of_create"
        exclude group: "dev.engine-room"
        exclude group: "dev.engine_room"
    }
    implementation("org.valkyrienskies.core:api:${rootProject.vscore_version}") {
        exclude group: 'org.joml', module: ''
    }
    implementation("org.valkyrienskies.core:impl:${rootProject.vscore_version}") {
        exclude group: 'org.joml', module: ''
    }
    implementation("org.valkyrienskies.core:internal:${rootProject.vscore_version}") {
        exclude group: 'org.joml', module: ''
    }

    implementation("org.joml:joml-primitives:1.10.0")
    implementation("org.joml:joml:1.10.4")

    // For unit testing.
    var kotestVersion = "5.4.1"
    testImplementation 'org.junit.jupiter:junit-jupiter-api:5.8.1'
    testRuntimeOnly 'org.junit.jupiter:junit-jupiter-engine:5.8.1'
    testImplementation("io.kotest:kotest-runner-junit5:$kotestVersion")
    testImplementation("io.kotest:kotest-property:$kotestVersion")
    testImplementation("io.kotest:kotest-assertions-core:$kotestVersion")
    testImplementation("io.mockk:mockk:1.12.5")
}
